import { Tenant, User } from '@/lib/db/schema';
import { CURRENT_SCHEMA_VERSION } from '../schema';
import { v4 as uuidv4 } from 'uuid';

const currentDate = new Date().toISOString();

export const TENANTS: Tenant[] = [
  {
    id: uuidv4(),
    name: 'Demo Proxy 1',
    type: 'proxy',
    createdAt: currentDate,
    active: true,
    version: CURRENT_SCHEMA_VERSION,
    admins: ['admin@demoproxy1.com'],
  },
  {
    id: uuidv4(),
    name: 'Demo Proxy 2',
    type: 'proxy',
    createdAt: currentDate,
    active: true,
    version: CURRENT_SCHEMA_VERSION,
    admins: ['admin@demoproxy2.com'],
  },
  {
    id: uuidv4(),
    name: 'Demo Provider',
    type: 'provider',
    createdAt: currentDate,
    active: true,
    version: CURRENT_SCHEMA_VERSION,
    requiredCustomerInfo: [
      'customerName',
      'customerEmail',
      'accountNumber',
      'lastFourCCDigits',
    ],
    admins: ['admin@demoprovider.com'],
  },
  {
    id: uuidv4(),
    name: 'ProxyLink Management',
    type: 'management',
    createdAt: currentDate,
    active: true,
    version: CURRENT_SCHEMA_VERSION,
    admins: ['sorokinvj@gmail.com', 'john@proxylink.co'],
  },
];

export const USERS: User[] = [
  {
    id: uuidv4(),
    email: 'employee1@demoprovider.com',
    firstName: 'Zephyr',
    lastName: 'Stormwind',
    tenantId: TENANTS[2].id,
    tenantName: TENANTS[2].name,
    tenantType: TENANTS[2].type,
    role: 'user',
    createdAt: currentDate,
    version: CURRENT_SCHEMA_VERSION,
  },
  {
    id: uuidv4(),
    email: 'admin@demoprovider.com',
    firstName: 'Admin',
    lastName: 'Starlight',
    tenantId: TENANTS[2].id,
    tenantName: TENANTS[2].name,
    tenantType: TENANTS[2].type,
    role: 'admin',
    createdAt: currentDate,
    version: CURRENT_SCHEMA_VERSION,
  },
  {
    id: uuidv4(),
    email: 'employee1@demoproxy1.com',
    firstName: 'Michael',
    lastName: 'Scott',
    tenantId: TENANTS[0].id,
    tenantName: TENANTS[0].name,
    tenantType: TENANTS[0].type,
    role: 'user',
    createdAt: currentDate,
    version: CURRENT_SCHEMA_VERSION,
  },
  {
    id: uuidv4(),
    email: 'admin@demoproxy1.com',
    firstName: 'Dwight',
    lastName: 'Schrute',
    tenantId: TENANTS[0].id,
    tenantName: TENANTS[0].name,
    tenantType: TENANTS[0].type,
    role: 'admin',
    createdAt: currentDate,
    version: CURRENT_SCHEMA_VERSION,
  },
  {
    id: uuidv4(),
    email: 'employee1@demoproxy2.com',
    firstName: 'James',
    lastName: 'Sawyer',
    tenantId: TENANTS[1].id,
    tenantName: TENANTS[1].name,
    tenantType: TENANTS[1].type,
    role: 'user',
    createdAt: currentDate,
    version: CURRENT_SCHEMA_VERSION,
  },
  {
    id: uuidv4(),
    email: 'admin@demoproxy2.com',
    firstName: 'Carol',
    lastName: 'Schulz',
    tenantId: TENANTS[1].id,
    tenantName: TENANTS[1].name,
    tenantType: TENANTS[1].type,
    role: 'admin',
    createdAt: currentDate,
    version: CURRENT_SCHEMA_VERSION,
  },
  {
    id: uuidv4(),
    email: 'sorokinvj@gmail.com',
    firstName: 'Vladislav',
    lastName: 'Sorokin',
    tenantId: TENANTS[3].id,
    tenantName: TENANTS[3].name,
    tenantType: TENANTS[3].type,
    role: 'admin',
    createdAt: currentDate,
    version: CURRENT_SCHEMA_VERSION,
  },
  {
    id: uuidv4(),
    email: 'john@proxylink.co',
    firstName: 'John',
    lastName: 'Walter',
    tenantId: TENANTS[3].id,
    tenantName: TENANTS[3].name,
    tenantType: TENANTS[3].type,
    role: 'admin',
    createdAt: currentDate,
    version: CURRENT_SCHEMA_VERSION,
  },
];

export const STANDARD_PASSWORD = 'q1w2e3';
